---
- name: Initialize Kubernetes on all Nodes
  hosts: all
  become: yes
  tasks:
    - name: disable firewall service for labs
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Disable SWAP
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

    - name: install containerd
          yum:
            name: containerd.io
            state: latest
            update_cache: yes

    - name: start containerd
      service:
        name: containerd
        state: started
        enabled: true

    - name: disable SELinux
      command: setenforce 0
      ignore_errors: yes

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: install kubelet, kubeadm, and kubectl
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: yes

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

  handlers:
    - name: reboot ALL machines
      reboot:
        message: "Rebooting for system changes"
        reboot_timeout: 300
