---
- name: Initialize Kubernetes on all Nodes
  hosts: all
  become: yes
  tasks:
    - name: Disable SWAP
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: latest

    - name: Start containerd
      service:
        name: containerd
        state: started
        enabled: true

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
      ignore_errors: yes

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: Install packages needed to use the Kubernetes apt repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: latest
        update_cache: yes

    - name: Download the Google Cloud public signing key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'

    - name: Add the Kubernetes apt repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-$(lsb_release -cs) main"
        create: yes

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Mark kubelet, kubeadm, and kubectl to hold
      ansible.builtin.apt_mark:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    - name: Reload systemd and start kubelet service
      systemd:
        daemon_reload: yes
        name: kubelet
        state: started
        enabled: yes
