---
- name: Initialize Kubernetes Cluster with kubeadm
  hosts: master
  become: yes
  tasks:
    - name: Initialize the Kubernetes cluster
      command: kubeadm init
      register: kubeadm_init

    - name: Ensure .kube directory exists
      file:
        path: "$HOME/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "$HOME/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: 0644

    - name: Output kubeadm join command to file
      copy:
        content: "{{ kubeadm_init.stdout_lines | select('search', 'kubeadm join') | first }}"
        dest: "/etc/kubernetes/kubeadm_join_cmd.sh"
        mode: 0755

    - name: Print the kubeadm join command
      debug:
        msg: "{{ kubeadm_init.stdout_lines | select('search', 'kubeadm join') | first }}"

- name: Set KUBECONFIG environment variable for the root user
  hosts: master
  become: yes
  tasks:
    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
        create: yes

- name: Deploy a pod network
  hosts: master
  become: yes
  tasks:
    - name: Deploy the chosen network solution
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      # Replace [podnetwork].yaml with the actual file for the network plugin
