- name: Initialize Kubernetes Cluster with kubeadm
  hosts: k8s-master
  become: yes
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: "$HOME/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "$HOME/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: 0644

    - name: Create kubeadm join command if not already done
      command: kubeadm token create --print-join-command
      register: kubeadm_join
      changed_when: false

    - name: Output kubeadm join command to file
      copy:
        content: "{{ kubeadm_join.stdout }}"
        dest: "/etc/kubernetes/kubeadm_join_cmd.sh"
        mode: 0755

    - name: Print the kubeadm join command
      debug:
        msg: "{{ kubeadm_join.stdout }}"

    - name: Deploy Calico network
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
