- name: Initialize Kubernetes Cluster with kubeadm
  hosts: master
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Ensure .kube directory exists in the ubuntu user's home
      file:
        path: "/home/ubuntu/.kube"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy admin.conf to the ubuntu user's kube config
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "/home/ubuntu/.kube/config"
        remote_src: yes
        force: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Create kubeadm join command if not already done
      command: kubeadm token create --print-join-command
      register: kubeadm_join
      changed_when: false
      ignore_errors: true

    - name: Output kubeadm join command to file
      copy:
        content: "{{ kubeadm_join.stdout }}"
        dest: "/etc/kubernetes/kubeadm_join_cmd.sh"
        mode: '0755'
      when: kubeadm_join is defined and kubeadm_join.stdout is defined

    - name: Print the kubeadm join command
      debug:
        msg: "{{ kubeadm_join.stdout }}"
      when: kubeadm_join is defined and kubeadm_join.stdout is defined

    - name: Deploy Calico network
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"
