---
- name: Initialize Kubernetes on all Nodes
  hosts: all
  become: yes
  tasks:
    - name: Disable SWAP
      command: swapoff -a
      ignore_errors: yes

    - name: Update fstab to disable swap
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        line: '# commented out by Ansible to disable swap'
        state: present

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package cache and install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: latest

    - name: Start and enable containerd service
      service:
        name: containerd
        state: started
        enabled: true

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Ensure sysctl settings for Kubernetes networking
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
        - { key: 'net.ipv4.ip_forward', value: '1' }

    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key
        state: present

    - name: Add Kubernetes APT repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /'
        state: present
        filename: kubernetes.list

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Mark kubelet, kubeadm, and kubectl to hold
      ansible.builtin.apt_mark:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    - name: Reload systemd and start kubelet service
      systemd:
        daemon_reload: yes
        name: kubelet
        state: started
        enabled: yes
