version: "3"
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

volumes:
  nexus_data:


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