apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-role-binding
  namespace: web-app
subjects:
- kind: ServiceAccount
  name: argocd-service-account   # Replace with the actual service account used by ArgoCD
  namespace: argocd  # Assuming ArgoCD is deployed in the 'argocd' namespace
roleRef:
  kind: Role
  name: argo-role
  apiGroup: rbac.authorization.k8s.io
